version: 0.0.1-alpha-{build}
pull_requests:
  do_not_increment_build_number: false
branches:
  only:
  - master
skip_tags: true
image: Visual Studio 2017
configuration: Release
before_build:
  - cmd: cd src
  - cmd: dotnet restore
  - cmd: cd ..
build:
  project: src/dataframe-utils.sln
  verbosity: minimal
  publish_nuget: true
artifacts:
  - path: '**\*.nupkg' # find all NuGet packages recursively
    name: dataframe-utils
test_script:
- cmd: cd src\dftest
- cmd: dotnet test
- cmd: cd ..
- cmd: cd ..
deploy:
  - provider: NuGet
    artifact: dataframe-utils
    api_key:
      secure: $(NUGET_KEY)
