version: 1.0.1-alpha-{build}
pull_requests:
  do_not_increment_build_number: false
branches:
  only:
  - master
skip_tags: true
image: Visual Studio 2017
configuration: Release
before_build:
- ps: .\appveyor.ps1
build:
  project: src/DataFrame.sln
  verbosity: minimal
artifacts:
  - path: src/**/*.nupkg
test_script:
- cmd: dotnet test src/Tests/DataFrame.Math.Tests
deploy:
- provider: Environment
  name: aloneguid NuGet