$version: 0.0.1-alpha-{build}
pull_requests:
  do_not_increment_build_number: true
branches:
  only:
  - master
skip_tags: true
image: Visual Studio 2017
configuration: Release
platform: Any CPU
before_build:
  - cmd: cd src
  - cmd: dotnet restore
  - cmd: cd ..
build:
  project: src/dataframe-utils.sln
  verbosity: minimal
test_script:
- cmd: cd src\dftest
- cmd: dotnet test
- cmd: cd ..
- cmd: cd ..
after_build:
  - cmd: cd src\dataframe-maths
  - cmd: dotnet pack dataframe-maths.csproj --configuration Release /p:Version="0.1.$(appveyor_build_number)"
artifacts:
  - path: src/dataframe-maths/bin/**/*.nupkg
